version: "3"

services:
  server:
    image: eidos-service.di.unito.it/dalmasso/federated-neve
    command: [ "python3", "server.py",
               "--server-address=localhost:6789",
               "--amp=1",
               "--device=cuda",
               "--batch-size=100",
               "--epochs=250",
               "--dataset-root=/scratch/datasets/classification/",
               "--dataset-name=cifar10",
               "--use-neve=0",
               "--seed=0" ]
    ports:
      - "6789:6789"
    volumes:
      - /mnt/fast-scratch/$USER:/scratch

  client0:
    image: eidos-service.di.unito.it/dalmasso/federated-neve
    command: [ "python3", "client.py",
               "--server-address=localhost:6789",
               "--current-client=0",
               "--amp=1",
               "--device=cuda",
               "--batch-size=100",
               "--epochs=250",
               "--dataset-root=/scratch/datasets/classification/",
               "--dataset-name=cifar10",
               "--use-neve=0",
               "--seed=0" ]
    depends_on:
      - server
    ports:
      - "6790:6790"
    volumes:
      - /mnt/fast-scratch/$USER:/scratch

  client1:
    image: eidos-service.di.unito.it/dalmasso/federated-neve:python
    command: [ "python3", "client.py",
               "--server-address=localhost:6789",
               "--current-client=1",
               "--amp=1",
               "--device=cuda",
               "--batch-size=100",
               "--epochs=250",
               "--dataset-root=/scratch/datasets/classification/",
               "--dataset-name=cifar10",
               "--use-neve=0",
               "--seed=0" ]
    depends_on:
      - server
    ports:
      - "6791:6791"
    volumes:
      - /mnt/fast-scratch/$USER:/scratch